### ISSUE TITLE
Addon relies on classes and methods that are not included in the addon

### ISSUE THREAD

**Issue by cenduroyib** [hen31/TurtleGamesBehaviorTree#1]
**Issue:**
The addon relies on classes and methods that are not included in the addon.
Missing references:
- `MyBakkery` in `TreeValue.cs`
- `SetNodeFromNodePath` in `SubBehaviorTreeNode.cs`.

**To Reproduce Steps to reproduce the behavior:**
Create an empty Godot Project and add the _TurtleGamesBehaviourTree_ addon.

**Expected behavior:**
Being able to run the project with the addon.

**Desktop (please complete the following information):**
    Platform: Windows
    Godot: 3.4.3-3.4.4

**Comment by hen31** [comment]
Fixed by removing the code
